micronaut:
  application:
    name: kotlintransactions-2
r2dbc:
  datasources:
    # default:
    accounts-datasource:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/accounts
      username: accounts
      password: secret
      ssl: DISABLED
      zeroDateOption: USE_NULL
netty:
  default:
    allocator:
      max-order: 3
