micronaut:
  application:
    name: kotlintransactions-2
r2dbc:
  datasources:
    # accounts-datasource:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://localhost:3306/accounts
      username: accounts
      password: secret
netty:
  default:
    allocator:
      max-order: 3
